/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareIdRouteImport } from './routes/share/$id'
import { Route as ApiSharesIndexRouteImport } from './routes/api/shares/index'
import { Route as ApiPublicSttRouteImport } from './routes/api/public/stt'
import { Route as ApiSharesIdIndexRouteImport } from './routes/api/shares/$id/index'
import { Route as ApiPublicSharesIndexRouteImport } from './routes/api/public/shares/index'
import { Route as ApiSharesIdSyncRouteImport } from './routes/api/shares/$id/sync'
import { Route as ApiSharesIdDataRouteImport } from './routes/api/shares/$id/data'
import { Route as ApiPublicSharesIdIndexRouteImport } from './routes/api/public/shares/$id/index'
import { Route as ApiPublicSharesIdSyncRouteImport } from './routes/api/public/shares/$id/sync'
import { Route as ApiPublicSharesIdDataRouteImport } from './routes/api/public/shares/$id/data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesIndexRoute = ApiSharesIndexRouteImport.update({
  id: '/api/shares/',
  path: '/api/shares/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSttRoute = ApiPublicSttRouteImport.update({
  id: '/api/public/stt',
  path: '/api/public/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesIdIndexRoute = ApiSharesIdIndexRouteImport.update({
  id: '/api/shares/$id/',
  path: '/api/shares/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSharesIndexRoute = ApiPublicSharesIndexRouteImport.update({
  id: '/api/public/shares/',
  path: '/api/public/shares/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesIdSyncRoute = ApiSharesIdSyncRouteImport.update({
  id: '/api/shares/$id/sync',
  path: '/api/shares/$id/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesIdDataRoute = ApiSharesIdDataRouteImport.update({
  id: '/api/shares/$id/data',
  path: '/api/shares/$id/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSharesIdIndexRoute = ApiPublicSharesIdIndexRouteImport.update({
  id: '/api/public/shares/$id/',
  path: '/api/public/shares/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSharesIdSyncRoute = ApiPublicSharesIdSyncRouteImport.update({
  id: '/api/public/shares/$id/sync',
  path: '/api/public/shares/$id/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSharesIdDataRoute = ApiPublicSharesIdDataRouteImport.update({
  id: '/api/public/shares/$id/data',
  path: '/api/public/shares/$id/data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share/$id': typeof ShareIdRoute
  '/api/public/stt': typeof ApiPublicSttRoute
  '/api/shares/': typeof ApiSharesIndexRoute
  '/api/shares/$id/data': typeof ApiSharesIdDataRoute
  '/api/shares/$id/sync': typeof ApiSharesIdSyncRoute
  '/api/public/shares/': typeof ApiPublicSharesIndexRoute
  '/api/shares/$id/': typeof ApiSharesIdIndexRoute
  '/api/public/shares/$id/data': typeof ApiPublicSharesIdDataRoute
  '/api/public/shares/$id/sync': typeof ApiPublicSharesIdSyncRoute
  '/api/public/shares/$id/': typeof ApiPublicSharesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share/$id': typeof ShareIdRoute
  '/api/public/stt': typeof ApiPublicSttRoute
  '/api/shares': typeof ApiSharesIndexRoute
  '/api/shares/$id/data': typeof ApiSharesIdDataRoute
  '/api/shares/$id/sync': typeof ApiSharesIdSyncRoute
  '/api/public/shares': typeof ApiPublicSharesIndexRoute
  '/api/shares/$id': typeof ApiSharesIdIndexRoute
  '/api/public/shares/$id/data': typeof ApiPublicSharesIdDataRoute
  '/api/public/shares/$id/sync': typeof ApiPublicSharesIdSyncRoute
  '/api/public/shares/$id': typeof ApiPublicSharesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/share/$id': typeof ShareIdRoute
  '/api/public/stt': typeof ApiPublicSttRoute
  '/api/shares/': typeof ApiSharesIndexRoute
  '/api/shares/$id/data': typeof ApiSharesIdDataRoute
  '/api/shares/$id/sync': typeof ApiSharesIdSyncRoute
  '/api/public/shares/': typeof ApiPublicSharesIndexRoute
  '/api/shares/$id/': typeof ApiSharesIdIndexRoute
  '/api/public/shares/$id/data': typeof ApiPublicSharesIdDataRoute
  '/api/public/shares/$id/sync': typeof ApiPublicSharesIdSyncRoute
  '/api/public/shares/$id/': typeof ApiPublicSharesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/share/$id'
    | '/api/public/stt'
    | '/api/shares/'
    | '/api/shares/$id/data'
    | '/api/shares/$id/sync'
    | '/api/public/shares/'
    | '/api/shares/$id/'
    | '/api/public/shares/$id/data'
    | '/api/public/shares/$id/sync'
    | '/api/public/shares/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/share/$id'
    | '/api/public/stt'
    | '/api/shares'
    | '/api/shares/$id/data'
    | '/api/shares/$id/sync'
    | '/api/public/shares'
    | '/api/shares/$id'
    | '/api/public/shares/$id/data'
    | '/api/public/shares/$id/sync'
    | '/api/public/shares/$id'
  id:
    | '__root__'
    | '/'
    | '/share/$id'
    | '/api/public/stt'
    | '/api/shares/'
    | '/api/shares/$id/data'
    | '/api/shares/$id/sync'
    | '/api/public/shares/'
    | '/api/shares/$id/'
    | '/api/public/shares/$id/data'
    | '/api/public/shares/$id/sync'
    | '/api/public/shares/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShareIdRoute: typeof ShareIdRoute
  ApiPublicSttRoute: typeof ApiPublicSttRoute
  ApiSharesIndexRoute: typeof ApiSharesIndexRoute
  ApiSharesIdDataRoute: typeof ApiSharesIdDataRoute
  ApiSharesIdSyncRoute: typeof ApiSharesIdSyncRoute
  ApiPublicSharesIndexRoute: typeof ApiPublicSharesIndexRoute
  ApiSharesIdIndexRoute: typeof ApiSharesIdIndexRoute
  ApiPublicSharesIdDataRoute: typeof ApiPublicSharesIdDataRoute
  ApiPublicSharesIdSyncRoute: typeof ApiPublicSharesIdSyncRoute
  ApiPublicSharesIdIndexRoute: typeof ApiPublicSharesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares/': {
      id: '/api/shares/'
      path: '/api/shares'
      fullPath: '/api/shares/'
      preLoaderRoute: typeof ApiSharesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stt': {
      id: '/api/public/stt'
      path: '/api/public/stt'
      fullPath: '/api/public/stt'
      preLoaderRoute: typeof ApiPublicSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares/$id/': {
      id: '/api/shares/$id/'
      path: '/api/shares/$id'
      fullPath: '/api/shares/$id/'
      preLoaderRoute: typeof ApiSharesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shares/': {
      id: '/api/public/shares/'
      path: '/api/public/shares'
      fullPath: '/api/public/shares/'
      preLoaderRoute: typeof ApiPublicSharesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares/$id/sync': {
      id: '/api/shares/$id/sync'
      path: '/api/shares/$id/sync'
      fullPath: '/api/shares/$id/sync'
      preLoaderRoute: typeof ApiSharesIdSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares/$id/data': {
      id: '/api/shares/$id/data'
      path: '/api/shares/$id/data'
      fullPath: '/api/shares/$id/data'
      preLoaderRoute: typeof ApiSharesIdDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shares/$id/': {
      id: '/api/public/shares/$id/'
      path: '/api/public/shares/$id'
      fullPath: '/api/public/shares/$id/'
      preLoaderRoute: typeof ApiPublicSharesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shares/$id/sync': {
      id: '/api/public/shares/$id/sync'
      path: '/api/public/shares/$id/sync'
      fullPath: '/api/public/shares/$id/sync'
      preLoaderRoute: typeof ApiPublicSharesIdSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shares/$id/data': {
      id: '/api/public/shares/$id/data'
      path: '/api/public/shares/$id/data'
      fullPath: '/api/public/shares/$id/data'
      preLoaderRoute: typeof ApiPublicSharesIdDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShareIdRoute: ShareIdRoute,
  ApiPublicSttRoute: ApiPublicSttRoute,
  ApiSharesIndexRoute: ApiSharesIndexRoute,
  ApiSharesIdDataRoute: ApiSharesIdDataRoute,
  ApiSharesIdSyncRoute: ApiSharesIdSyncRoute,
  ApiPublicSharesIndexRoute: ApiPublicSharesIndexRoute,
  ApiSharesIdIndexRoute: ApiSharesIdIndexRoute,
  ApiPublicSharesIdDataRoute: ApiPublicSharesIdDataRoute,
  ApiPublicSharesIdSyncRoute: ApiPublicSharesIdSyncRoute,
  ApiPublicSharesIdIndexRoute: ApiPublicSharesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
